### ISSUE TITLE
missing SCM rockspecs

### ISSUE THREAD

**Issue by catwell** [arcapos/rockspecs#3]
- [ ] [json](https://github.com/arcapos/luajson) (we need another name for LuaRocks)
- [ ] [motif](https://github.com/arcapos/luamotif) 
- [ ] [curl](https://github.com/arcapos/luacurl) 
- [ ] [nanomsg](https://github.com/arcapos/luananomsg) 
- [ ] [zmq](https://github.com/arcapos/luazmq) 
- [ ] [fcgi](https://github.com/arcapos/luafcgi)

**Comment by mbalmer** [comment]
We can not rename the json module, if that conflicts with an existint LuaRocks module, we can, however, rename the rock.  I don't know if that is doable.  If not, maybe we should not put this JSON module on LuaRocks (maybe compared to the zillion other JSON modules anyways).

As for the other modules, yes, we are waiting for people who want them in LuaRocks and who are willing to spend a bit of time to create a rockspec file.  That is what we created arcapos/rockspecs for.

(Keep in mind:  We don't use LuaRocks, but we want to make it as easy as possible for people who'd like to see some of our modules/bindings in LuaRocks to do so).

**Comment by catwell** [comment]
Yes, I was thinking of writing some or all of those myself.

As for the JSON module, I meant what you said: name the rock something else, such as arcapos-json, not the module. But as you said it is probably not that useful to add one more JSON module to LuaRocks.

Something completely unrelated: do you happen to have some tests, or at least some example code that would help verify that the modules built by the rockspecs actually work?

**Comment by mbalmer** [comment]
We think that our JSON module is quite usable, and we use it in production.  If possible, I'd love to see it in LuaRocks.  The name can be arcapos-json, jsona, yajson (yet another json) or whatever...

As for the tests, these modules are used in production systems at many sites all over the country, they are thoroughly tested by human beings, any malfunction would immediately lead to phone calls...  That said, we have something better than CI/automated tests :)

**Comment by catwell** [comment]
I wasn't thinking about finding bugs in the modules, I was thinking about finding bugs in the rockspecs themselves. For instance, you can build luaunix without `-lcrypt` on Linux, but it will fail at runtime. I found that thanks to `server.lua` from luanet.

Tests / sample code would also serve as documentations for some of those modules I guess, since they have no documentation otherwise (or maybe I didn't look in the right place...).

**Comment by mbalmer** [comment]
Maybe such a (basic) runtime test should be a feature of LuaRocks itself, e.g. after building and installing a module running 'lua -c "require 'modname'" ?  But I am not sure that would work, since a module can also return a function that needs to be called etc.  What would make in sense in your mind?

**Comment by catwell** [comment]
Loading the module is the minimum, having actual tests that run code from the module, even without full coverage, is better.

I think Hisham wants to support tests in the next major version of LuaRocks through an add-on system, but they are not really supported yet.

**Comment by mbalmer** [comment]
Timeout.
