### ISSUE TITLE
Upload to luarocks.org

### ISSUE THREAD

**Issue by daurnimator** [arcapos/rockspecs#5]
@mbalmer, please upload all rockspecs to luarocks.org.

You can do so via your browser at https://luarocks.org/upload
Or using the luarocks command line tool: `luarocks upload foo.rockspec`

**Comment by catwell** [comment]
@daurnimator Also we need to make "release" rockspecs for those that are only available as SCM for now.

Also, not sure if @mbalmer wants to upload the rockspecs himself. Otherwise we could probably do it. We could even create an arcapos account with an email address he controls and use an API token to manage it.

**Comment by mbalmer** [comment]
> Am 15.02.2016 um 10:23 schrieb Pierre Chapuis notifications@github.com:
> 
> @daurnimator Also we need to make "release" rockspecs for those that are only available as SCM for now.
> 
> Also, not sure if @mbalmer wants to upload the rockspecs himself. Otherwise we could probably do it. We could even create an arcapos account with an email address he controls and use an API token to manage it.

If you can handle this, that would be much appreciated.  If you need an @arcapos.com email address for this, that would be no problem.

**Comment by daurnimator** [comment]
> Also, not sure if @mbalmer wants to upload the rockspecs himself. Otherwise we could probably do it. We could even create an arcapos account with an email address he controls and use an API token to manage it.

Some of the rockspecs are already uploaded under his account: https://luarocks.org/modules/mbalmer
We'd have to move them over to a new account I guess.
Or mbalmer could give us api tokens for his personal account?

**Comment by mbalmer** [comment]
I think I uploaded all them by now.  I am slowly working on converting the scm rockspecs to versioned ones.  I close the issue for now.
