### ISSUE TITLE
luanet rockspec

### ISSUE THREAD

**Issue by hineios** [arcapos/rockspecs#6]
I believe you have a typo on the luanet.rockspec
In the source part it should be `http://github.com/arcapos/luanet/archive/1.1.2.zip` instead of `http://github.com/mbalmer/luapgsql/archive/1.1.2.zip`, right?

**Comment by mbalmer** [comment]
Oh yes, indeed.  Can you bake a pull request?

Am 30.01.17 um 17:09 schrieb Fábio Vieira Almeida:

**Comment by hineios** [comment]
Off course. https://github.com/arcapos/rockspecs/pull/7

**Comment by hineios** [comment]
Just a follow up, this will update the rock on luarocks, right?

**Comment by mbalmer** [comment]
No, I thin I will have to upload it manually, I will take care.


Am 31.01.17 um 13:34 schrieb Fábio Vieira Almeida:

**Comment by hineios** [comment]
Great.
Many thanks.
